use crate::ast::*;
use std::collections::HashMap;

/// Production-grade LLVM IR emitter for the Grit compiler.
/// Emits SSA-form LLVM IR that can be compiled with `clang` or `llc`.
pub struct LLVMEmitter {
    output: String,
    reg: u32,           // SSA register counter
    label_id: u32,      // label counter for branches
    str_id: u32,        // string constant counter
    strings: Vec<(String, usize)>,  // (value, byte_len including null)
    /// Maps local variable names to their alloca register
    locals: HashMap<String, u32>,
}

impl LLVMEmitter {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            reg: 0,
            label_id: 0,
            str_id: 0,
            strings: Vec::new(),
            locals: HashMap::new(),
        }
    }

    fn next_reg(&mut self) -> u32 {
        let r = self.reg;
        self.reg += 1;
        r
    }

    fn next_label(&mut self, prefix: &str) -> String {
        let id = self.label_id;
        self.label_id += 1;
        format!("{}.{}", prefix, id)
    }

    fn line(&mut self, s: &str) {
        self.output.push_str(s);
        self.output.push('\n');
    }

    // ── Program emission ─────────────────────────────────

    pub fn emit_program(&mut self, program: &SourceFile) -> String {
        // Pre-pass: collect all string constants
        for item in &program.items {
            if let Item::Function(f) = item {
                if let Some(body) = &f.body {
                    self.collect_strings_block(body);
                }
            }
        }

        // Header
        self.line("; ── Grit LLVM IR ─────────────────────────────────────");
        self.line("; Generated by gritc");
        self.line("target triple = \"x86_64-pc-windows-msvc\"");
        self.line("");

        // External declarations
        self.line("; ── External declarations ──");
        self.line("declare i32 @printf(i8*, ...)");
        self.line("declare i32 @puts(i8*)");
        self.line("declare void @exit(i32)");
        self.line("");

        // String constants
        if !self.strings.is_empty() {
            self.line("; ── String constants ──");
            for (id, (s, len)) in self.strings.clone().iter().enumerate() {
                let escaped = Self::escape_llvm_string(s);
                self.line(&format!(
                    "@.str.{} = private unnamed_addr constant [{} x i8] c\"{}\\0A\\00\"",
                    id, len, escaped
                ));
            }
            self.line("");
        }

        // Functions
        for item in &program.items {
            match item {
                Item::Function(f) if !f.is_comptime => {
                    self.emit_function(f);
                }
                _ => {}
            }
        }

        self.output.clone()
    }

    fn escape_llvm_string(s: &str) -> String {
        let mut out = String::new();
        for ch in s.chars() {
            match ch {
                '\\' => out.push_str("\\5C"),
                '"' => out.push_str("\\22"),
                '\n' => out.push_str("\\0A"),
                '\t' => out.push_str("\\09"),
                '\r' => out.push_str("\\0D"),
                '\0' => out.push_str("\\00"),
                _ => out.push(ch),
            }
        }
        out
    }

    // ── String collection pre-pass ───────────────────────

    fn collect_strings_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.collect_strings_stmt(stmt);
        }
        if let Some(expr) = &block.trailing_expr {
            self.collect_strings_expr(expr);
        }
    }

    fn collect_strings_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(l) => self.collect_strings_expr(&l.value),
            Stmt::Var(v) => { if let Some(val) = &v.value { self.collect_strings_expr(val); } }
            Stmt::Expr(e) => self.collect_strings_expr(&e.expr),
            Stmt::Assign(a) => { self.collect_strings_expr(&a.target); self.collect_strings_expr(&a.value); }
            Stmt::Return(r) => { if let Some(v) = &r.value { self.collect_strings_expr(v); } }
            _ => {}
        }
    }

    fn collect_strings_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::StringLiteral(s, _) => {
                if !self.strings.iter().any(|(v, _)| v == s) {
                    let len = s.len() + 2; // +\n +\0
                    self.strings.push((s.clone(), len));
                }
            }
            Expr::Call { args, callee, .. } => {
                self.collect_strings_expr(callee);
                for a in args { self.collect_strings_expr(&a.value); }
            }
            Expr::Binary { left, right, .. } => {
                self.collect_strings_expr(left);
                self.collect_strings_expr(right);
            }
            Expr::Unary { operand, .. } => self.collect_strings_expr(operand),
            Expr::If { condition, then_block, else_block, .. } => {
                self.collect_strings_expr(condition);
                self.collect_strings_block(then_block);
                if let Some(eb) = else_block { self.collect_strings_block(eb); }
            }
            Expr::While { condition, body, .. } => {
                self.collect_strings_expr(condition);
                self.collect_strings_block(body);
            }
            Expr::For { iterator, body, .. } => {
                self.collect_strings_expr(iterator);
                self.collect_strings_block(body);
            }
            Expr::Loop { body, .. } => self.collect_strings_block(body),
            Expr::Block(b) => self.collect_strings_block(b),
            _ => {}
        }
    }

    // ── Function emission ────────────────────────────────

    fn emit_function(&mut self, f: &FnDecl) {
        self.reg = 0;
        self.label_id = 0;
        self.locals.clear();

        let is_main = f.name == "main";
        let ret_ty = if is_main {
            "i32".to_string()
        } else {
            Self::resolve_return_type(f.return_type.as_deref())
        };

        // Build params
        let params_str = if f.params.is_empty() {
            String::new()
        } else {
            f.params.iter().map(|p| {
                let ty = Self::resolve_param_type(p.ty.as_deref());
                format!("{} %{}", ty, p.name)
            }).collect::<Vec<_>>().join(", ")
        };

        let fn_name = if is_main { "main".to_string() } else { format!("grit_{}", f.name) };

        self.line(&format!("define {} @{}({}) {{", ret_ty, fn_name, params_str));
        self.line("entry:");

        // Allocate space for parameters so they can be mutated
        for p in &f.params {
            let ty = Self::resolve_param_type(p.ty.as_deref());
            let alloca_reg = self.next_reg();
            self.line(&format!("  %{} = alloca {}", alloca_reg, ty));
            self.line(&format!("  store {} %{}, {}* %{}", ty, p.name, ty, alloca_reg));
            self.locals.insert(p.name.clone(), alloca_reg);
        }

        if let Some(body) = &f.body {
            self.emit_block_ir(body);
        }

        // Default return
        if is_main {
            self.line("  ret i32 0");
        } else {
            match ret_ty.as_str() {
                "void" => self.line("  ret void"),
                "i32" => self.line("  ret i32 0"),
                "i64" => self.line("  ret i64 0"),
                "double" => self.line("  ret double 0.0"),
                "i1" => self.line("  ret i1 0"),
                _ => self.line("  ret void"),
            }
        }

        self.line("}");
        self.line("");
    }

    // ── Block / statement emission ───────────────────────

    fn emit_block_ir(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.emit_stmt_ir(stmt);
        }
    }

    fn emit_stmt_ir(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Expr(e) => { self.emit_expr_ir(&e.expr); }
            Stmt::Let(l) => {
                if let Some(val_reg) = self.emit_expr_ir(&l.value) {
                    let ty = Self::infer_llvm_type(&l.value);
                    let alloca = self.next_reg();
                    self.line(&format!("  %{} = alloca {}", alloca, ty));
                    self.line(&format!("  store {} %{}, {}* %{}", ty, val_reg, ty, alloca));
                    if let Pattern::Ident(name, _) = &l.pattern {
                        self.locals.insert(name.clone(), alloca);
                    }
                }
            }
            Stmt::Var(v) => {
                let ty = if let Some(val) = &v.value {
                    Self::infer_llvm_type(val)
                } else {
                    "i32".to_string()
                };
                let alloca = self.next_reg();
                self.line(&format!("  %{} = alloca {}", alloca, ty));
                if let Some(val) = &v.value {
                    if let Some(val_reg) = self.emit_expr_ir(val) {
                        self.line(&format!("  store {} %{}, {}* %{}", ty, val_reg, ty, alloca));
                    }
                }
                self.locals.insert(v.name.clone(), alloca);
            }
            Stmt::Assign(a) => {
                if let Expr::Ident(name, _) = &a.target {
                    if let Some(&alloca) = self.locals.get(name) {
                        let ty = "i32";
                        match a.op {
                            AssignOp::Eq => {
                                if let Some(val_reg) = self.emit_expr_ir(&a.value) {
                                    self.line(&format!("  store {} %{}, {}* %{}", ty, val_reg, ty, alloca));
                                }
                            }
                            _ => {
                                let load_reg = self.next_reg();
                                self.line(&format!("  %{} = load {}, {}* %{}", load_reg, ty, ty, alloca));
                                if let Some(rhs_reg) = self.emit_expr_ir(&a.value) {
                                    let op_str = match a.op {
                                        AssignOp::PlusEq => "add",
                                        AssignOp::MinusEq => "sub",
                                        AssignOp::StarEq => "mul",
                                        AssignOp::SlashEq => "sdiv",
                                        AssignOp::PercentEq => "srem",
                                        _ => "add",
                                    };
                                    let result = self.next_reg();
                                    self.line(&format!("  %{} = {} {} %{}, %{}", result, op_str, ty, load_reg, rhs_reg));
                                    self.line(&format!("  store {} %{}, {}* %{}", ty, result, ty, alloca));
                                }
                            }
                        }
                    }
                }
            }
            Stmt::Return(r) => {
                if let Some(val) = &r.value {
                    let ty = Self::infer_llvm_type(val);
                    if let Some(val_reg) = self.emit_expr_ir(val) {
                        self.line(&format!("  ret {} %{}", ty, val_reg));
                    }
                } else {
                    self.line("  ret void");
                }
            }
            _ => {}
        }
    }

    // ── Expression emission ──────────────────────────────

    fn emit_expr_ir(&mut self, expr: &Expr) -> Option<u32> {
        match expr {
            Expr::IntLiteral(n, _) => {
                let r = self.next_reg();
                self.line(&format!("  %{} = add i32 0, {}", r, n));
                Some(r)
            }
            Expr::FloatLiteral(f, _) => {
                let r = self.next_reg();
                self.line(&format!("  %{} = fadd double 0.0, {:.15e}", r, f));
                Some(r)
            }
            Expr::BoolLiteral(b, _) => {
                let r = self.next_reg();
                self.line(&format!("  %{} = add i1 0, {}", r, if *b { 1 } else { 0 }));
                Some(r)
            }
            Expr::CharLiteral(c, _) => {
                let r = self.next_reg();
                self.line(&format!("  %{} = add i8 0, {}", r, *c as u32));
                Some(r)
            }
            Expr::Ident(name, _) => {
                if let Some(&alloca) = self.locals.get(name) {
                    let r = self.next_reg();
                    self.line(&format!("  %{} = load i32, i32* %{}", r, alloca));
                    Some(r)
                } else {
                    None
                }
            }
            Expr::Binary { left, op, right, .. } => {
                let l = self.emit_expr_ir(left)?;
                let r = self.emit_expr_ir(right)?;
                let result = self.next_reg();
                let ty = Self::infer_llvm_type(left);
                let is_float = ty == "double" || ty == "float";

                match op {
                    BinOp::Eq | BinOp::NotEq | BinOp::Less | BinOp::Greater
                    | BinOp::LessEq | BinOp::GreaterEq => {
                        let (prefix, cmp) = if is_float {
                            ("fcmp", match op {
                                BinOp::Eq => "oeq", BinOp::NotEq => "one",
                                BinOp::Less => "olt", BinOp::Greater => "ogt",
                                BinOp::LessEq => "ole", BinOp::GreaterEq => "oge",
                                _ => "oeq",
                            })
                        } else {
                            ("icmp", match op {
                                BinOp::Eq => "eq", BinOp::NotEq => "ne",
                                BinOp::Less => "slt", BinOp::Greater => "sgt",
                                BinOp::LessEq => "sle", BinOp::GreaterEq => "sge",
                                _ => "eq",
                            })
                        };
                        self.line(&format!("  %{} = {} {} {} %{}, %{}", result, prefix, cmp, ty, l, r));
                    }
                    BinOp::And => {
                        self.line(&format!("  %{} = and i1 %{}, %{}", result, l, r));
                    }
                    BinOp::Or => {
                        self.line(&format!("  %{} = or i1 %{}, %{}", result, l, r));
                    }
                    _ => {
                        let instr = if is_float {
                            match op {
                                BinOp::Add => "fadd", BinOp::Sub => "fsub",
                                BinOp::Mul => "fmul", BinOp::Div => "fdiv",
                                _ => "fadd",
                            }
                        } else {
                            match op {
                                BinOp::Add => "add", BinOp::Sub => "sub",
                                BinOp::Mul => "mul", BinOp::Div => "sdiv",
                                BinOp::Mod => "srem",
                                BinOp::BitAnd => "and", BinOp::BitOr => "or",
                                BinOp::BitXor => "xor", BinOp::Shl => "shl", BinOp::Shr => "ashr",
                                _ => "add",
                            }
                        };
                        self.line(&format!("  %{} = {} {} %{}, %{}", result, instr, ty, l, r));
                    }
                }
                Some(result)
            }
            Expr::Unary { op, operand, .. } => {
                let val = self.emit_expr_ir(operand)?;
                let result = self.next_reg();
                match op {
                    UnaryOp::Neg => {
                        let ty = Self::infer_llvm_type(operand);
                        if ty == "double" {
                            self.line(&format!("  %{} = fneg double %{}", result, val));
                        } else {
                            self.line(&format!("  %{} = sub {} 0, %{}", result, ty, val));
                        }
                    }
                    UnaryOp::Not => {
                        self.line(&format!("  %{} = xor i1 %{}, 1", result, val));
                    }
                    UnaryOp::BitNot => {
                        self.line(&format!("  %{} = xor i32 %{}, -1", result, val));
                    }
                    _ => return Some(val),
                }
                Some(result)
            }
            Expr::Call { callee, args, .. } => {
                if let Expr::Ident(name, _) = callee.as_ref() {
                    if name == "print" {
                        if let Some(arg) = args.first() {
                            if let Expr::StringLiteral(s, _) = &arg.value {
                                let str_idx = self.strings.iter().position(|(v, _)| v == s).unwrap_or(0);
                                let len = self.strings[str_idx].1;
                                let r = self.next_reg();
                                self.line(&format!(
                                    "  %{} = call i32 (i8*, ...) @printf(i8* getelementptr ([{} x i8], [{} x i8]* @.str.{}, i32 0, i32 0))",
                                    r, len, len, str_idx
                                ));
                                return Some(r);
                            }
                        }
                        return None;
                    }
                    // Regular function call
                    let mut arg_regs = Vec::new();
                    for arg in args {
                        if let Some(reg) = self.emit_expr_ir(&arg.value) {
                            let ty = Self::infer_llvm_type(&arg.value);
                            arg_regs.push((ty, reg));
                        }
                    }
                    let args_str = arg_regs.iter()
                        .map(|(ty, reg)| format!("{} %{}", ty, reg))
                        .collect::<Vec<_>>().join(", ");
                    let r = self.next_reg();
                    self.line(&format!("  %{} = call i32 @grit_{}({})", r, name, args_str));
                    return Some(r);
                }
                None
            }
            Expr::If { condition, then_block, else_block, .. } => {
                let cond_reg = self.emit_expr_ir(condition)?;
                let then_label = self.next_label("then");
                let else_label = self.next_label("else");
                let merge_label = self.next_label("merge");

                if else_block.is_some() {
                    self.line(&format!("  br i1 %{}, label %{}, label %{}", cond_reg, then_label, else_label));
                } else {
                    self.line(&format!("  br i1 %{}, label %{}, label %{}", cond_reg, then_label, merge_label));
                }

                self.line(&format!("{}:", then_label));
                self.emit_block_ir(then_block);
                self.line(&format!("  br label %{}", merge_label));

                if let Some(eb) = else_block {
                    self.line(&format!("{}:", else_label));
                    self.emit_block_ir(eb);
                    self.line(&format!("  br label %{}", merge_label));
                }

                self.line(&format!("{}:", merge_label));
                None
            }
            Expr::While { condition, body, .. } => {
                let cond_label = self.next_label("while.cond");
                let body_label = self.next_label("while.body");
                let end_label = self.next_label("while.end");

                self.line(&format!("  br label %{}", cond_label));
                self.line(&format!("{}:", cond_label));
                let cond_reg = self.emit_expr_ir(condition)?;
                self.line(&format!("  br i1 %{}, label %{}, label %{}", cond_reg, body_label, end_label));

                self.line(&format!("{}:", body_label));
                self.emit_block_ir(body);
                self.line(&format!("  br label %{}", cond_label));

                self.line(&format!("{}:", end_label));
                None
            }
            Expr::Loop { body, .. } => {
                let loop_label = self.next_label("loop");
                let end_label = self.next_label("loop.end");

                self.line(&format!("  br label %{}", loop_label));
                self.line(&format!("{}:", loop_label));
                self.emit_block_ir(body);
                self.line(&format!("  br label %{}", loop_label));
                self.line(&format!("{}:", end_label));
                None
            }
            Expr::For { pattern, iterator, body, .. } => {
                if let Pattern::Ident(name, _) = pattern.as_ref() {
                    if let Expr::Range { start, end, .. } = iterator.as_ref() {
                        let start_val = if let Some(s) = start {
                            self.emit_expr_ir(s).unwrap_or(0)
                        } else {
                            let r = self.next_reg();
                            self.line(&format!("  %{} = add i32 0, 0", r));
                            r
                        };

                        let loop_var = self.next_reg();
                        self.line(&format!("  %{} = alloca i32", loop_var));
                        self.line(&format!("  store i32 %{}, i32* %{}", start_val, loop_var));
                        self.locals.insert(name.clone(), loop_var);

                        let cond_label = self.next_label("for.cond");
                        let body_label = self.next_label("for.body");
                        let end_label = self.next_label("for.end");

                        self.line(&format!("  br label %{}", cond_label));
                        self.line(&format!("{}:", cond_label));

                        let cur = self.next_reg();
                        self.line(&format!("  %{} = load i32, i32* %{}", cur, loop_var));

                        let end_val = if let Some(e) = end {
                            self.emit_expr_ir(e).unwrap_or(0)
                        } else {
                            let r = self.next_reg();
                            self.line(&format!("  %{} = add i32 0, 0", r));
                            r
                        };

                        let cmp_reg = self.next_reg();
                        self.line(&format!("  %{} = icmp slt i32 %{}, %{}", cmp_reg, cur, end_val));
                        self.line(&format!("  br i1 %{}, label %{}, label %{}", cmp_reg, body_label, end_label));

                        self.line(&format!("{}:", body_label));
                        self.emit_block_ir(body);

                        let reload = self.next_reg();
                        self.line(&format!("  %{} = load i32, i32* %{}", reload, loop_var));
                        let next_val = self.next_reg();
                        self.line(&format!("  %{} = add i32 %{}, 1", next_val, reload));
                        self.line(&format!("  store i32 %{}, i32* %{}", next_val, loop_var));
                        self.line(&format!("  br label %{}", cond_label));

                        self.line(&format!("{}:", end_label));
                        return None;
                    }
                }
                None
            }
            Expr::Block(block) => {
                self.emit_block_ir(block);
                None
            }
            _ => None,
        }
    }

    // ── Type helpers (all static — no &self borrows) ─────

    fn resolve_return_type(ty: Option<&TypeExpr>) -> String {
        match ty {
            None => "void".to_string(),
            Some(t) => Self::type_expr_to_llvm(t),
        }
    }

    fn resolve_param_type(ty: Option<&TypeExpr>) -> String {
        match ty {
            None => "i32".to_string(),
            Some(t) => Self::type_expr_to_llvm(t),
        }
    }

    fn type_expr_to_llvm(ty: &TypeExpr) -> String {
        match ty {
            TypeExpr::Path(path, _) => {
                let name = path.join(".");
                match name.as_str() {
                    "i8" | "u8" => "i8",
                    "i16" | "u16" => "i16",
                    "i32" | "u32" => "i32",
                    "i64" | "u64" => "i64",
                    "i128" | "u128" => "i128",
                    "isize" | "usize" => "i64",
                    "f32" => "float",
                    "f64" => "double",
                    "bool" => "i1",
                    "char" => "i8",
                    "String" => "i8*",
                    "type" => "i32",
                    _ => "i32",
                }.to_string()
            }
            _ => "i32".to_string(),
        }
    }

    fn infer_llvm_type(expr: &Expr) -> String {
        match expr {
            Expr::IntLiteral(_, _) => "i32".to_string(),
            Expr::FloatLiteral(_, _) => "double".to_string(),
            Expr::BoolLiteral(_, _) => "i1".to_string(),
            Expr::CharLiteral(_, _) => "i8".to_string(),
            Expr::StringLiteral(_, _) => "i8*".to_string(),
            Expr::Binary { op, .. } => {
                match op {
                    BinOp::Eq | BinOp::NotEq | BinOp::Less | BinOp::Greater
                    | BinOp::LessEq | BinOp::GreaterEq | BinOp::And | BinOp::Or
                    => "i1".to_string(),
                    _ => "i32".to_string(),
                }
            }
            _ => "i32".to_string(),
        }
    }
}
